apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
spec:
  selector:
    matchLabels:
      app: yolo5
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      containers:
      - name: yolo5
        image: 854171615125.dkr.ecr.us-west-1.amazonaws.com/sangini-jenkins-repo:20
        ports:
        - containerPort: 8082

apiVersion: v1
kind: Service
metadata:
  name: yolo5
spec:
  selector:
    app: yolo5
  ports:
    - port: 8082
      targetPort: 8082